#!/bin/sh
# TODO: Configure the remote host
REMOTE_HOST=51.210.191.243
REMOTE_USER=ubuntu

# Open SSH port with UPnP
# LOCAL_IP=$(ip -4 addr show eno1 | grep -oP '(?<=inet\s)\d+(\.\d+){3}')

# Get Public IP
PUBLIC_IP=$(upnpc -s | grep -Po 'ExternalIPAddress = \K(.*)')

# Open SSH port with UPnP
upnpc -c $PUBLIC_IP 22 22 TCP


# Send the IP
echo "$PUBLIC_IP\n" | ssh -i nuc_key $REMOTE_USER@$REMOTE_HOST "cat >> ip_list"


